name: kevin-bioinformatics
channels:
  - conda-forge
  - nvidia
  - defaults
  - pytorch
dependencies:
  - _libavif_api=1.3.0=h57928b3_2
  - _py-xgboost-mutex=2.0=cpu_0
  - _python_abi3_support=1.0=hd8ed1ab_2
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.12.15=py312h05f76fc_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - alabaster=1.0.0=pyhd8ed1ab_1
  - anyio=4.10.0=pyhe01879c_0
  - aom=3.9.1=he0c23c2_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py312he06e257_0
  - arrow=1.3.0=pyhd8ed1ab_1
  - astroid=3.3.11=py312h2e8e312_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - asyncssh=2.21.0=pyhd8ed1ab_0
  - atomicwrites=1.4.1=pyhd8ed1ab_1
  - attrs=25.3.0=pyh71513ae_0
  - autopep8=2.0.4=pyhd8ed1ab_0
  - babel=2.17.0=pyhd8ed1ab_0
  - backports=1.0=pyhd8ed1ab_5
  - backports.tarfile=1.2.0=pyhd8ed1ab_1
  - bcrypt=4.3.0=py312hdabe01f_2
  - beautifulsoup4=4.13.5=pyha770c72_0
  - binaryornot=0.4.4=pyhd8ed1ab_2
  - black=25.1.0=pyh866005b_0
  - blas=1.0=mkl
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - boruta_py=0.3=pyhd8ed1ab_1
  - brotli=1.1.0=hfd05255_4
  - brotli-bin=1.1.0=hfd05255_4
  - brotli-python=1.1.0=py312hbb81ca0_4
  - bzip2=1.0.8=h2466b09_7
  - ca-certificates=2025.11.12=h4c7d964_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h5782bbf_0
  - catboost=1.2.5=py312h2e8e312_0
  - category_encoders=2.9.0=pyhcf101f3_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=1.17.1=py312he06e257_1
  - chardet=5.2.0=pyhd8ed1ab_3
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - click=8.2.1=pyh7428d3b_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py312hf90b1b7_2
  - cookiecutter=2.6.0=pyhd8ed1ab_1
  - cpython=3.12.11=py312hd8ed1ab_0
  - cryptography=45.0.7=py312h84d000f_1
  - cuda-cccl=13.0.50=h23517cc_1
  - cuda-cccl_win-64=13.0.50=hc667259_1
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvrtc-dev=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=13.0.39=0
  - cuda-opencl-dev=13.0.39=0
  - cuda-profiler-api=13.0.39=0
  - cuda-runtime=12.1.0=0
  - cuda-version=13.0=3
  - cycler=0.12.1=pyhd8ed1ab_1
  - dav1d=1.2.1=hcfcfb64_0
  - dcm2niix=1.0.20250506=h8918064_1
  - debugpy=1.8.16=py312ha1a9051_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecated=1.2.18=pyhd8ed1ab_0
  - dicom2nifti=2.3.4=pyhd3deb0d_0
  - diff-match-patch=20241021=pyhd8ed1ab_1
  - dill=0.4.0=pyhd8ed1ab_0
  - docstring-to-markdown=0.17=pyhe01879c_0
  - docutils=0.21.2=pyhd8ed1ab_1
  - double-conversion=3.3.1=he0c23c2_0
  - eigen=3.4.0=h91493d7_0
  - entrypoints=0.4=pyhd8ed1ab_1
  - et_xmlfile=2.0.0=pyhd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - ffmpeg=8.0.0=gpl_h70aa942_903
  - fftw=3.3.10=nompi_h89e6982_110
  - filelock=3.19.1=pyhd8ed1ab_0
  - flake8=7.1.2=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.59.2=py312h05f76fc_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freeglut=3.2.2=he0c23c2_3
  - freetype=2.13.3=h57928b3_1
  - fribidi=1.0.10=h8d14728_0
  - frozenlist=1.7.0=py312hfdf67e6_0
  - fzf=0.65.2=hb13f615_0
  - gdk-pixbuf=2.42.12=h1f5b9c4_3
  - getopt-win32=0.1=h6a83c73_3
  - glib=2.84.3=h36503ca_0
  - glib-tools=2.84.3=he647baa_0
  - glslang=15.4.0=h5b34520_0
  - graphite2=1.3.14=hac47afa_2
  - graphviz=13.1.2=ha5e8f4b_0
  - gst-plugins-base=1.24.11=h3fe0a9e_0
  - gstreamer=1.24.11=h233a61a_0
  - gts=0.7.6=h6b5321d_4
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=11.4.5=h5f2951f_0
  - hdf5=1.14.6=nompi_he30205f_103
  - highdicom=0.27.0=pyhd8ed1ab_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he0c23c2_0
  - idna=3.10=pyhd8ed1ab_1
  - imagesize=1.4.1=pyhd8ed1ab_0
  - imath=3.2.1=h1608b31_0
  - imbalanced-learn=0.14.0=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - inflection=0.5.1=pyhd8ed1ab_1
  - intel-openmp=2025.2.0=h57928b3_757
  - intervaltree=3.1.0=pyhd8ed1ab_1
  - ipykernel=6.29.5=pyh4bbf305_0
  - ipython=8.37.0=pyha7b4d00_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.7=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - isort=6.0.1=pyhd8ed1ab_1
  - jaraco.classes=3.4.0=pyhd8ed1ab_2
  - jaraco.context=6.0.1=pyhd8ed1ab_0
  - jaraco.functools=4.3.0=pyhd8ed1ab_0
  - jasper=4.2.8=h8ad263b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jellyfish=1.1.3=py312h2615798_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py312h2e8e312_2
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.4.1=pyh29332c3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter=1.1.1=pyhd8ed1ab_1
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=7.4.9=pyhd8ed1ab_0
  - jupyter_console=6.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh5737063_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.6=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - jupyterlab_widgets=3.0.15=pyhd8ed1ab_0
  - keyring=25.6.0=pyh7428d3b_0
  - khronos-opencl-icd-loader=2024.10.24=h2466b09_1
  - kiwisolver=1.4.9=py312h78d62e6_1
  - krb5=1.21.3=hdf4eb48_0
  - lame=3.100=hcfcfb64_1003
  - lark=1.2.2=pyhd8ed1ab_1
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libabseil=20250512.1=cxx17_habfad5f_0
  - libaec=1.1.4=h20038f6_0
  - libasprintf=0.22.5=h5728263_3
  - libavif16=1.3.0=he916da2_2
  - libblas=3.9.0=1_h8933c1f_netlib
  - libbrotlicommon=1.1.0=hfd05255_4
  - libbrotlidec=1.1.0=hfd05255_4
  - libbrotlienc=1.1.0=hfd05255_4
  - libcblas=3.9.0=12_hb3dda5d_netlib
  - libclang13=21.1.0=default_hadf22e1_0
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufft-dev=11.0.2.4=0
  - libcurand=10.4.0.35=0
  - libcurand-dev=10.4.0.35=0
  - libcurl=8.14.1=h88aaa65_0
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libdeflate=1.24=h76ddb4d_0
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.4.6=h537db12_1
  - libfreetype=2.13.3=h57928b3_1
  - libfreetype6=2.13.3=h0b5ce68_1
  - libgd=2.3.3=h7208af6_11
  - libgettextpo=0.22.5=h5728263_3
  - libglib=2.84.3=h1c1036b_0
  - libhwloc=2.12.1=default_hfa10c62_1000
  - libhwy=1.3.0=h47aaa27_0
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libintl-devel=0.22.5=h5728263_3
  - libitk=5.4.4=h8ef7100_0
  - libjpeg-turbo=3.1.0=h2466b09_0
  - libjxl=0.11.1=h98f49f0_3
  - liblapack=3.9.0=12_h13b7882_netlib
  - liblapacke=3.9.0=12_h1360930_netlib
  - liblzma=5.8.1=h2466b09_2
  - libnpp=12.0.2.50=0
  - libnpp-dev=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libnvjpeg-dev=12.1.1.14=0
  - libogg=1.3.5=h2466b09_1
  - libopencv=4.12.0=qt6_py312h0541d9f_604
  - libopenvino=2025.2.0=hbf28c98_1
  - libopenvino-auto-batch-plugin=2025.2.0=hdd9a157_1
  - libopenvino-auto-plugin=2025.2.0=hdd9a157_1
  - libopenvino-hetero-plugin=2025.2.0=hc39e7c6_1
  - libopenvino-intel-cpu-plugin=2025.2.0=hbf28c98_1
  - libopenvino-intel-gpu-plugin=2025.2.0=hbf28c98_1
  - libopenvino-ir-frontend=2025.2.0=hc39e7c6_1
  - libopenvino-onnx-frontend=2025.2.0=hee3bb10_1
  - libopenvino-paddle-frontend=2025.2.0=hee3bb10_1
  - libopenvino-pytorch-frontend=2025.2.0=hac47afa_1
  - libopenvino-tensorflow-frontend=2025.2.0=h293fe96_1
  - libopenvino-tensorflow-lite-frontend=2025.2.0=hac47afa_1
  - libopus=1.5.2=h2466b09_0
  - libpng=1.6.50=h7351971_1
  - libprotobuf=6.31.1=hdcda5b4_1
  - librsvg=2.58.4=h5ce5fed_3
  - libsodium=1.0.20=hc70643c_0
  - libspatialindex=2.1.0=h518811d_0
  - libsqlite=3.50.4=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libtiff=4.7.0=h550210a_6
  - libusb=1.0.29=h1839187_0
  - libuv=1.51.0=hfd05255_1
  - libvorbis=1.3.7=h5112557_2
  - libwebp=1.6.0=h4d5522a_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libxcb=1.16=h013a479_1
  - libxgboost=2.1.3=cpu_hb3f76d0_1
  - libxml2=2.13.8=h741aa76_1
  - libxslt=1.1.43=h25c3957_0
  - libzlib=1.3.1=h2466b09_2
  - llvmlite=0.45.1=py312hdb9728c_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.2=py312h31fea79_1
  - matplotlib=3.10.5=py312h2e8e312_0
  - matplotlib-base=3.10.5=py312h0ebf65c_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mccabe=0.7.0=pyhd8ed1ab_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mistune=3.1.4=pyhcf101f3_0
  - mkl=2023.1.0=h6a75c08_48682
  - more-itertools=10.8.0=pyhd8ed1ab_0
  - mpmath=1.3.0=pyhd8ed1ab_1
  - mrmr_selection=0.2.8=pyhd8ed1ab_1
  - msys2-conda-epoch=20160418=1
  - multidict=6.6.3=py312h05f76fc_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - mypy_extensions=1.1.0=pyha770c72_0
  - narwhals=2.6.0=pyhcf101f3_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert=7.16.6=hb482800_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbconvert-pandoc=7.16.6=hed9df3c_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.5=pyhe01879c_0
  - nibabel=5.3.2=pyha770c72_1
  - notebook=7.4.5=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numba=0.62.1=py312h9a042f1_0
  - numpydoc=1.9.0=pyhe01879c_1
  - opencl-headers=2025.06.13=he0c23c2_0
  - opencv=4.12.0=qt6_py312h64de955_604
  - openexr=3.3.5=hed76565_1
  - openh264=2.6.0=hb17fa0b_0
  - openjpeg=2.5.3=h24db6dd_1
  - openpyxl=3.1.5=py312h83acffa_2
  - openssl=3.6.0=h725018a_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.2=py312hc128f0a_0
  - pandoc=3.7.0.2=h57928b3_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.56.4=h03d888a_0
  - parso=0.8.5=pyhcf101f3_0
  - pathspec=0.12.1=pyhd8ed1ab_1
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.45=h99c9b8b_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=10.4.0=py312h381445a_1
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h5112557_1
  - platformdirs=4.4.0=pyhcf101f3_0
  - plotly=6.3.1=pyhd8ed1ab_0
  - pluggy=1.6.0=pyhd8ed1ab_0
  - ply=3.11=pyhd8ed1ab_3
  - polars=1.35.1=pyh6a1acc5_0
  - polars-runtime-32=1.35.1=py310hca7251b_0
  - prometheus_client=0.22.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - prompt_toolkit=3.0.52=hd8ed1ab_0
  - propcache=0.3.1=py312h31fea79_0
  - psutil=7.0.0=py312he06e257_1
  - pthread-stubs=0.4=hcd874cb_1001
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pugixml=1.15=h372dad0_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-opencv=4.12.0=qt6_py312h4c995e2_604
  - py-xgboost=2.1.3=cpu_pyh1ce2f49_1
  - pycodestyle=2.12.1=pyhd8ed1ab_1
  - pyconify=0.2.1=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pydicom=3.0.1=pyhd8ed1ab_2
  - pydocstyle=6.3.0=pyhd8ed1ab_1
  - pyflakes=3.2.0=pyhd8ed1ab_1
  - pygithub=2.8.0=pyhd8ed1ab_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyjpegls=1.5.1=py312hf4e254d_2
  - pyjwt=2.10.1=pyhd8ed1ab_0
  - pylint=3.3.8=pyhe01879c_0
  - pylint-venv=3.0.4=pyhd8ed1ab_1
  - pyls-spyder=0.4.0=pyhd8ed1ab_1
  - pynacl=1.5.0=py312he06e257_5
  - pynrrd=0.4.2=pyh95af2a2_0
  - pyopenssl=25.1.0=pyhd8ed1ab_0
  - pyparsing=3.2.3=pyhe01879c_2
  - pyqt=5.15.11=py312he11f4ca_1
  - pyqt5-sip=12.17.0=py312h275cf98_1
  - pyqtwebengine=5.15.11=py312h5f40ce4_1
  - pyside6=6.9.2=py312h0ba07f7_1
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.12.11=h3f84c4b_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-gil=3.12.11=hd8ed1ab_0
  - python-graphviz=0.21=pyhbacfb6d_0
  - python-gssapi=1.9.0=py312hd572b79_2
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-lsp-black=2.0.0=pyhff2d567_1
  - python-lsp-jsonrpc=1.1.2=pyhff2d567_1
  - python-lsp-server=1.12.2=pyhff2d567_0
  - python-lsp-server-base=1.12.2=pyhd8ed1ab_0
  - python-slugify=8.0.4=pyhd8ed1ab_1
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.12=8_cp312
  - pytoolconfig=1.2.5=pyhd8ed1ab_1
  - pytorch=2.5.1=py3.12_cuda12.1_cudnn9_0
  - pytorch-cuda=12.1=hde6ce7c_6
  - pytorch-mutex=1.0=cuda
  - pytz=2025.2=pyhd8ed1ab_0
  - pyuca=1.2=pyhd8ed1ab_2
  - pywin32=311=py312h829343e_1
  - pywin32-ctypes=0.2.3=py312h2e8e312_2
  - pywinpty=2.0.15=py312h275cf98_0
  - pyyaml=6.0.2=py312h31fea79_2
  - pyzmq=24.0.1=py312h2bbff1b_0
  - qdarkstyle=3.2.3=pyhd8ed1ab_1
  - qhull=2020.2=hc790b64_5
  - qstylizer=0.2.4=pyhff2d567_0
  - qt-main=5.15.15=hb098fff_5
  - qt-webengine=5.15.15=h087ee03_1
  - qt6-main=6.9.2=h236c7cd_0
  - qtawesome=1.4.0=pyh9208f05_1
  - qtconsole=5.6.1=pyhd8ed1ab_2
  - qtconsole-base=5.6.1=pyha770c72_2
  - qtpy=2.4.3=pyhd8ed1ab_1
  - rav1e=0.7.1=ha073cba_3
  - referencing=0.36.2=pyh29332c3_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rich=14.1.0=pyhe01879c_0
  - roman-numerals-py=3.1.0=pyhd8ed1ab_0
  - rope=1.14.0=pyhd8ed1ab_0
  - rpds-py=0.27.1=py312hdabe01f_1
  - rtree=1.4.1=pyh11ca60a_0
  - scikit-learn=1.7.2=py312h91ac024_0
  - scipy=1.16.1=py312h33376e8_1
  - sdl2=2.32.54=he0c23c2_0
  - sdl3=3.2.22=h5112557_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - send2trash=1.8.3=pyh5737063_1
  - setuptools=80.9.0=pyhff2d567_0
  - shaderc=2025.3=haa9a63f_1
  - shap=0.48.0=cpu_py312h923d338_1
  - simpleitk=2.5.2=py312h73a9f73_1
  - sip=6.10.0=py312h275cf98_0
  - six=1.17.0=pyhe01879c_1
  - slicer=0.0.8=pyhd8ed1ab_0
  - snappy=1.2.2=h7fa0ca8_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - snowballstemmer=3.0.1=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - soupsieve=2.8=pyhd8ed1ab_0
  - sphinx=8.3.0=pyhd8ed1ab_0
  - sphinxcontrib-applehelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-devhelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-htmlhelp=2.1.0=pyhd8ed1ab_1
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_1
  - sphinxcontrib-qthelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-serializinghtml=1.1.10=pyhd8ed1ab_1
  - spirv-tools=2025.1=hc790b64_0
  - spyder=6.0.8=hd8ed1ab_0
  - spyder-base=6.0.8=py312h2e8e312_0
  - spyder-kernels=3.0.5=win_pyh7428d3b_0
  - spyder-notebook=0.6.1=pyhd8ed1ab_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.5=py312h196c9fc_0
  - superqt=0.7.6=pyhb6d5dde_0
  - svt-av1=3.1.2=hac47afa_0
  - tbb=2021.13.0=h18a62a1_3
  - terminado=0.18.1=pyh5737063_0
  - text-unidecode=1.3=pyhd8ed1ab_2
  - textdistance=4.6.3=pyhd8ed1ab_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - three-merge=0.1.1=pyhd8ed1ab_1
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=h2c6b04d_2
  - toml=0.10.2=pyhd8ed1ab_1
  - tomli=2.2.1=pyhe01879c_2
  - tomlkit=0.13.3=pyha770c72_0
  - tornado=6.5.2=py312he06e257_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-python-dateutil=2.9.0.20250822=pyhd8ed1ab_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.26100.0=h57928b3_0
  - ujson=5.11.0=py312ha1a9051_1
  - unicodedata2=16.0.0=py312he06e257_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - vc=14.3=h41ae7f8_31
  - vc14_runtime=14.44.35208=h818238b_31
  - vcomp14=14.44.35208=h818238b_31
  - vs2015_runtime=14.44.35208=h38c0c73_31
  - watchdog=6.0.0=py312h2e8e312_1
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - whatthepatch=1.0.7=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.14=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - winpty=0.4.3=4
  - wrapt=1.17.3=py312he06e257_1
  - x264=1!164.3095=h8ffe710_2
  - x265=3.5=h2d74725_3
  - xgboost=2.1.3=cpu_pyhc1a9e11_1
  - xorg-kbproto=1.0.7=hcd874cb_1002
  - xorg-libice=1.1.1=hcd874cb_0
  - xorg-libsm=1.2.4=hcd874cb_0
  - xorg-libx11=1.8.9=h0076a8d_1
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xorg-libxext=1.3.4=hcd874cb_2
  - xorg-libxpm=3.5.17=hcd874cb_0
  - xorg-libxt=1.3.0=hcd874cb_1
  - xorg-xextproto=7.3.0=hcd874cb_1003
  - xorg-xproto=7.0.31=hcd874cb_1007
  - yaml=0.2.5=h6a83c73_3
  - yapf=0.43.0=pyhd8ed1ab_1
  - yarl=1.20.1=py312h31fea79_0
  - zeromq=4.3.5=ha9f60a1_7
  - zipp=3.23.0=pyhd8ed1ab_0
  - zstandard=0.24.0=py312ha680012_0
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - albucore==0.0.24
      - albumentations==2.0.8
      - annotated-types==0.7.0
      - fsspec==2025.9.0
      - lightning-utilities==0.15.2
      - numpy==2.2.6
      - opencv-python-headless==4.12.0.88
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - simsimd==6.5.1
      - stringzilla==3.12.6
      - sympy==1.13.1
      - torchaudio==2.5.1
      - torchmetrics==1.8.1
      - torchvision==0.20.1
      - typing-inspection==0.4.1
prefix: C:\Users\VI-01\anaconda3\envs\kevin-bioinformatics
